/* This file was automatically generated on Thu 26 May 2016 16:08:02 BST from
 * source: /home/hgv27681/R3.14.12.3/support/smaractEcm/etc/makeIocs/testM4.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

